# Stage builder
FROM ruby:3.0.0-alpine as Builder
RUN apk add --update --no-cache build-base git imagemagick nodejs-current yarn tzdata

WORKDIR /app
ADD Gemfile* /app/

RUN bundle config --global frozen 1 \
 && bundle install --without development test -j4 --retry 3 \
 # Remove unneeded files (cached *.gem, *.o, *.c)
 && rm -rf /usr/local/bundle/cache/*.gem \
 && find /usr/local/bundle/gems/ -name "*.c" -delete \
 && find /usr/local/bundle/gems/ -name "*.o" -delete


# Install yarn packages
COPY package.json yarn.lock /app/
RUN yarn install

# Add the Rails app
ADD . /app

# Remove folders not needed in resulting image
RUN rm -rf node_modules tmp/cache app/assets vendor/assets lib/assets spec

# Stage Final
FROM ruby:3.0.0

RUN apk add --update --no-cache \
    postgresql-client \
    imagemagick \
    tzdata \
    file \

# Copy app with gems from former build stage
COPY --from=Builder /usr/local/bundle/ /usr/local/bundle/
COPY --from=Builder --chown=app:app /app /app

WORKDIR /app

# Expose port
EXPOSE 3000

# Start up
CMD ["rails", "server", "-b", "0.0.0.0"]
